/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TailorsRouteImport } from './routes/tailors'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ChatTailorIdRouteImport } from './routes/chat.$tailorId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorsRoute = TailorsRouteImport.update({
  id: '/tailors',
  path: '/tailors',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ChatTailorIdRoute = ChatTailorIdRouteImport.update({
  id: '/$tailorId',
  path: '/$tailorId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/premium': typeof PremiumRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/tailors': typeof TailorsRoute
  '/wishlist': typeof WishlistRoute
  '/chat/$tailorId': typeof ChatTailorIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/premium': typeof PremiumRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/tailors': typeof TailorsRoute
  '/wishlist': typeof WishlistRoute
  '/chat/$tailorId': typeof ChatTailorIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/premium': typeof PremiumRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/tailors': typeof TailorsRoute
  '/wishlist': typeof WishlistRoute
  '/chat/$tailorId': typeof ChatTailorIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/orders'
    | '/premium'
    | '/shop'
    | '/splash'
    | '/tailors'
    | '/wishlist'
    | '/chat/$tailorId'
    | '/orders/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/orders'
    | '/premium'
    | '/shop'
    | '/splash'
    | '/tailors'
    | '/wishlist'
    | '/chat/$tailorId'
    | '/orders/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/orders'
    | '/premium'
    | '/shop'
    | '/splash'
    | '/tailors'
    | '/wishlist'
    | '/chat/$tailorId'
    | '/orders/$id'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  ShopRoute: typeof ShopRoute
  SplashRoute: typeof SplashRoute
  TailorsRoute: typeof TailorsRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailors': {
      id: '/tailors'
      path: '/tailors'
      fullPath: '/tailors'
      preLoaderRoute: typeof TailorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/chat/$tailorId': {
      id: '/chat/$tailorId'
      path: '/$tailorId'
      fullPath: '/chat/$tailorId'
      preLoaderRoute: typeof ChatTailorIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatTailorIdRoute: typeof ChatTailorIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatTailorIdRoute: ChatTailorIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PremiumRoute: PremiumRoute,
  ShopRoute: ShopRoute,
  SplashRoute: SplashRoute,
  TailorsRoute: TailorsRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
